### ISSUE TITLE
Crash on Android 4.2.2

### ISSUE THREAD

**Issue by kumold** [mikepenz/Android-Iconics#438] opened 2019-03-13 05:16 UTC
## About this issue

- Iconic initialization fails with whole app crash in Android SDK 17 (4.2.2) on 
`Iconics.init(getApplicationContext());`

Error log follows:
`03-13 05:09:41.562 18272-18272/com.mikepenz.iconics.sample.debug E/AndroidRuntime: FATAL EXCEPTION: main

    java.lang.NoClassDefFoundError: com.mikepenz.iconics.animation.IconicsAnimationProcessor$2
        at com.mikepenz.iconics.animation.IconicsAnimationProcessor.<init>(IconicsAnimationProcessor.java:139)
        at com.mikepenz.iconics.animation.BlinkAlphaProcessor.<init>(BlinkAlphaProcessor.java:31)
        at java.lang.Class.newInstanceImpl(Native Method)
        at java.lang.Class.newInstance(Class.java:1319)
        at com.mikepenz.iconics.Iconics.init(Iconics.java:73)
        at com.mikepenz.iconics.Iconics.getRegisteredFonts(Iconics.java:171)
        at com.mikepenz.iconics.sample.MainActivity.onCreate(MainActivity.java:77)
        at android.app.Activity.performCreate(Activity.java:5104)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
        at android.app.ActivityThread.access$600(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5041)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
        at dalvik.system.NativeStart.main(Native Method)`

## Details
- [3.2.1] Used library version
- [1.0.0-beta01] Used support library version
- [4.10.2-gradle, 3.3.0 - gradle plugin] Used gradle build tools version
- [3.3.2 Android studio] Used tooling / Android Studio version
- [x] Other used libraries, potential conflicting libraries

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/Android-Iconics/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/Android-Iconics/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/Android-Iconics/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/Android-Iconics/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/Android-Iconics/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md)

**Comment by mikepenz** [comment] 2019-03-13 10:01
Seems like a duplicate of: https://github.com/mikepenz/Android-Iconics/issues/436

**Closed by mikepenz** 2019-03-13 10:01 UTC
