### ISSUE TITLE
Image flickering

### ISSUE THREAD

**Issue by hareesh145** [mikepenz/Android-Iconics#232] opened 2016-10-27 11:42 UTC
Hi

When i am entering any text in the edit text iconic image view is flickering.

Thanks in advance

**Comment by mikepenz** [comment] 2016-10-27 14:55
@hareesh145 `IconicImageView`? So you have a `EditText` and beside this a `IconicsImageView`? 

Those 2 views are independent. So it is no issue of the lib. You can also see something like this in the sample applications playground / automatic mapping activity where you can enter without any flickering or other ui glitches

**Comment by hareesh145** [comment] 2016-10-28 05:15
@mikepenz  With default ImageView i am not getting issue

**Comment by mikepenz** [comment] 2016-10-28 05:42
@hareesh145 please provide a sample application showcasing this issue then.

**Comment by mikepenz** [comment] 2016-11-13 11:54
I close this as I can't reproduce this without a samle

**Closed by mikepenz** 2016-11-13 11:54 UTC
Labels: question
