### ISSUE TITLE
Icons are rendered as squares after dialog show or switch to another activity on API 19 and 21

### ISSUE THREAD

**Issue by stepanov-standy** [mikepenz/Android-Iconics#427] opened 2019-01-21 10:39 UTC
First of all let me thank you for great solutions that you made. I use both your libraries Iconics and Material Drawer in almost all my projects.

## About this issue
Icons are rendered as squares after dialog show or switch to another activity on API 19 and 21 (IconicsTextView, IconicsButton)

## Details
Please see the following short [video](https://drive.google.com/file/d/1C4CqiD1aczRYWwXqmCgCJ-eN9OJ0QTTp/view?usp=sharing) from Firebase Test Lab (0'53 time for example). I've found this during reviewing results of test lab. I don't have physical device with Android 4, I tried to reproduce on virtual device, but unfortunately without success :( On the other hand issue is reproduces 100% on both physical and virtual devices used in Firebase Test Lab (API 19 and 21). No issues on APIs 22+, not able to check on APIs 18-, because Firebase Test Lab provides only 19+ APIs.

Originally I have old version of your libraries, but even I've updated the app to the latest code with AndroidX support, issue still persists.

- Fragment of my layout xml:
```xml
    <LinearLayout
        android:id="@+id/bottom_menu"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="?bottomMenuBg"
        android:gravity="center_horizontal">

        <com.mikepenz.iconics.view.IconicsButton
            android:id="@+id/menu_delete_btn"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_weight="1"
            android:background="?attr/selectableItemBackground"
            android:paddingTop="3dp"
            android:tag="3"
            android:text="{cmd-close-box-outline}"
            android:textColor="?iconsColor"
            android:textSize="33sp" />

        <com.mikepenz.iconics.view.IconicsButton
            android:id="@+id/menu_load_from_file_btn"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_weight="1"
            android:background="?attr/selectableItemBackground"
            android:paddingTop="3dp"
            android:tag="3"
            android:text="{cmd-image}"
            android:textColor="?iconsColor"
            android:textSize="32sp" />

        <com.mikepenz.iconics.view.IconicsButton
            android:id="@+id/menu_camera_btn"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_weight="1"
            android:background="?attr/selectableItemBackground"
            android:paddingTop="3dp"
            android:tag="2"
            android:text="{cmd-camera}"
            android:textColor="?iconsColor"
            android:textSize="35sp" />

        <com.mikepenz.iconics.view.IconicsButton
            android:id="@+id/menu_add_by_keyboard_btn"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_weight="1"
            android:background="?attr/selectableItemBackground"
            android:paddingTop="3dp"
            android:tag="4"
            android:text="{cmd-playlist-plus}"
            android:textColor="?iconsColor"
            android:textSize="35sp" />

        <com.mikepenz.iconics.view.IconicsButton
            android:id="@+id/menu_add_user_btn"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_weight="1"
            android:background="?attr/selectableItemBackground"
            android:paddingTop="3dp"
            android:tag="1"
            android:text="{cmd-account}"
            android:textColor="?iconsColor"
            android:textSize="35sp" />
    </LinearLayout>
```

- Used library version
```gradle
implementation 'com.mikepenz:iconics-core:3.1.0'
implementation "com.mikepenz:iconics-views:3.1.0"
implementation 'com.mikepenz:fontawesome-typeface:4.7.0.2@aar'
implementation 'com.mikepenz:community-material-typeface:2.0.46.1@aar'
implementation 'com.mikepenz:google-material-typeface:3.0.1.2.original@aar'
```
- Used support library version
```gradle
implementation 'androidx.legacy:legacy-support-v4:1.0.0'
implementation 'androidx.browser:browser:1.0.0'
implementation 'androidx.media:media:1.0.0'
implementation 'androidx.recyclerview:recyclerview:1.0.0'
implementation 'androidx.appcompat:appcompat:1.0.2'
implementation "androidx.annotation:annotation:1.0.1"
implementation "androidx.constraintlayout:constraintlayout:2.0.0-alpha3"
implementation 'androidx.paging:paging-runtime:2.0.0'
```

- Used gradle build tools version
```gradle
compileSdkVersion 28
buildToolsVersion '28.0.3'
minSdkVersion 15
targetSdkVersion 26
```

- Used tooling / Android Studio version
3.3.0 Android Studio

- Other used libraries, potential conflicting libraries
```gradle
implementation 'com.mikepenz:materialdrawer:6.1.2'
```

**Comment by mikepenz** [comment] 2019-01-21 13:03
Is the same issue reproducible with the sample application?

**Comment by mikepenz** [comment] 2019-02-08 15:26
Please report back if you have new information :)

**Comment by stepanov-standy** [comment] 2019-02-09 14:24
Hello Mike, sorry for the delay, I am still busy with a new release of my app. I will try to clone your test project and deploy it to firebase test lab on upcoming week. I will let you know as soon as I get first results :)

**Comment by mikepenz** [comment] 2019-03-18 01:48
I will close this for the time being, as we were not able to reproduce this. Please open again when we can reproduce it :) 

Thanks a lot for the report.

**Closed by mikepenz** 2019-03-18 01:48 UTC
Labels: question

**Comment by stepanov-standy** [comment] 2019-03-19 09:49
Hello Mike,

I am so sorry for keeping you waiting. Finally I've deployed your demo project to firebase test lab, no issues on API 19 and 21 were detected. Looks like it is combination of libraries that I use in my project. Android 4 is not so popular now, moreover nobody from my users has informed me about this problem. Looks like impact is low for me, plan to keep it as is :) Keep up your great work!

**Comment by mikepenz** [comment] 2019-03-19 10:05
@stepanov-standy thank you so much. please let us know if it pops up again or when we can somehow work out whats going on :)
